# Unique name for this workflow
name: (1) Integration - Deploy on branch change

# Definition when the workflow should run
on:
    push:
      branches: [ integration ]
      paths:
        - 'force-app/**'
        - 'destructive/**'


# Jobs to be execute
jobs:
    Deploy-on-Integration-Sandbox:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            # Now we install Nodejs in the VM, on latest version
            - uses: actions/setup-node@v3
              with:
                node-version: 'latest'

            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                  mkdir ~/sf
                  tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
                  echo "$HOME/sf/bin" >> $GITHUB_PATH
                  ~/sf/bin/sf version

            # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
            - name: 'Installing sf git delta'
              run: |
                  echo y | sf plugins:install sfdx-git-delta
                  sf plugins

            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            # Store secret for both otgs
            - name: 'Populate auth file with SFDX_URL secret of the integration and staging orgs'
              shell: bash
              run: |
                  echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

            - name: 'Create delta packages for new, modified or deleted metadata'
              run: |
                  mkdir changed-sources
                  sf sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

            # Authenticate to Integration org
            - name: 'Authenticate to Integration Org'
              run: sf org login sfdx-url -f ./SFDX_INTEGRATION_URL.txt -s -a integration

            - name: 'Deploy Delta Changes to Integration org'
              if: ${{contains(github.event.head_commit[0].modified, 'force-app/')}}
              run: sf project deploy start --source-dir "changed-sources/force-app" --test-level RunLocalTests  --json

            - name: 'Deploy destructive changes (if any)'
              if: ${{contains(github.event.head_commit[0].modified, 'destructive/')}}
              run: sf project deploy start --manifest destructive/package.xml --post-destructive-changes destructive/destructiveChangesPost.xml --test-level RunLocalTests --json
