# Unique name for this workflow
name: (1) Destructive Changes - Validation or Deployment PR

# Definition when the workflow should run
on:
    # The workflow will run whenever an event happens on a pull request
    pull_request:

    # The events are that a PR is opened, or when a commit is pushed
    # to a branch that has an existing pull request
        types: [opened, reopened, synchronize]
        # The branches filter allows to specify that this workflow should only
        # run if the branch name is "integration". This way we prevent this workflow
        # from running when PRs are opened on other branches
        branches: [ integration, uat, main ]
        # We only care about changes to the force-app directory, which is the
        # root directory of the sfdx project. This prevents the job from running
        # when changing non-salesforce files (like this yml file).
        paths:
            - 'destructive/**'
    push:
        branches: [ integration, uat, main ]
        paths:
            - 'destructive/**'


# Jobs to be executed when the above conditions are met
jobs:
    # This is the name of the job. You can give it whatever name you want
    Validation-on-Destructive-Changes:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            # Now we install Nodejs in the VM, and specify latest version
            - uses: actions/setup-node@v3
              with:
                node-version: 'latest'

            # The idea is that the VM can access your remote repository
            # because your repository is an sfdx project.
            # This is a default action that allows us to enter the root
            # directory of the repository

            # Make sure to specify fetch-depth:0. This allows us to
            # access previous commits that have been pushed to the repository.

            # We'll need this later when we try to figure out which metadata has
            # changed between commits, so that we can only deploy that metadata
            # to the destination org

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            # Now Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                    wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                    mkdir ~/sf
                    tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
                    echo "$HOME/sf/bin" >> $GITHUB_PATH
                    ~/sf/bin/sf version

            # Install java as it is required for the next step
            - name: 'Installing java'
              run: |
                    sudo apt-get update
                    sudo apt-get install openjdk-8-jdk

            # Install SFDX scanner
            - name: 'Installing SF scanner'
              run: sf plugins install @salesforce/sfdx-scanner

            # Prior to setting up this workflow, you have to create a Github Secret
            # that contains the sfdx url of the integration org.

            # The steps to generate the url are here
            # https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm

            # This URL can then be used with the sfdx auth:sfdxurl:store to authenticate
            # the sfdx project in the repository, against the org from which the URL
            # was generated from. This works just like that, there's no need to create
            # connected apps or any else.

            # The URL is stored in the Github Secret named SFDX_INTEGRATION_URL
            # so here we store the URL into a text file
            - name: 'Populate auth file and Authenticate with SF_URL secret of org'
              shell: bash
              run: |
                echo ${{ github.ref }}
                if [[ ("${{github.event.pull_request.base.ref}}" = "main") || ("${{github.ref}}" = "refs/heads/main")]];
                then
                  echo ${{ secrets.SFDX_PRODUCTION_URL}} > ./SFDX_PRODUCTION_URL.txt
                  sf org login sfdx-url -f ./SFDX_PRODUCTION_URL.txt -s -a production
                elif [[ ("${{github.event.pull_request.base.ref}}" = "uat") || ("${{github.ref}}" = "refs/heads/uat")]];
                then
                  echo ${{ secrets.SFDX_UAT_URL}} > ./SFDX_UAT_URL.txt
                  sf org login sfdx-url -f ./SFDX_UAT_URL.txt -s -a uat
                elif [[ ("${{github.event.pull_request.base.ref}}" = "integration") || ("${{github.ref}}" = "refs/heads/integration")]];
                then
                  echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt
                  sf org login sfdx-url -f ./SFDX_INTEGRATION_URL.txt -s -a integration
                fi

            - name: 'Validate or Deploy Destructive changes'
              shell: bash
              run: |
                if [[ ("${{github.event_name}}" = "pull_request")]];
                then
                  sf project deploy start --manifest destructive/package.xml --post-destructive-changes destructive/destructiveChangesPost.xml --test-level RunLocalTests --dry-run --json
                elif [[ ("${{github.event_name}}" = "push")]];
                then
                  sf project deploy start --manifest destructive/package.xml --post-destructive-changes destructive/destructiveChangesPost.xml --test-level RunLocalTests --json
                fi
